# add gamelogic #
prefix_line(1)
def gold(here) # (1)
prefix_line(2)
  case var
  when :treasure # (3)
prefix_line(4)
    return "Yippieh!"  # (4)
prefix_line(5)
  else  # (5)
prefix_line(6)
    return "No treasure :(" # (6)
prefix_line(7)
end # (7)
prefix_line(8)
end # (8)
prefix_line(9)
puts gold(look(:front)) # (9)
