fun = {:line => lambda { |number| new_line ...
       :debug => lambda { |name_index, *val...
       :move => lambda { @ship.move!(packet) },
       :turn => lambda { |dir| @ship.turn!(...
       ...}
